// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: protos/raft.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendEntriesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      string                 `protobuf:"bytes,3,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	PrevLogIndex  int64                  `protobuf:"varint,4,opt,name=prevLogIndex,proto3" json:"prevLogIndex,omitempty"`
	PrevLogTerm   int64                  `protobuf:"varint,5,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	LeaderCommit  int64                  `protobuf:"varint,6,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesReq) Reset() {
	*x = AppendEntriesReq{}
	mi := &file_protos_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesReq) ProtoMessage() {}

func (x *AppendEntriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesReq.ProtoReflect.Descriptor instead.
func (*AppendEntriesReq) Descriptor() ([]byte, []int) {
	return file_protos_raft_proto_rawDescGZIP(), []int{0}
}

func (x *AppendEntriesReq) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesReq) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesReq) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *AppendEntriesReq) GetPrevLogIndex() int64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesReq) GetPrevLogTerm() int64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesReq) GetLeaderCommit() int64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type AppendEntriesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResp) Reset() {
	*x = AppendEntriesResp{}
	mi := &file_protos_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResp) ProtoMessage() {}

func (x *AppendEntriesResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResp.ProtoReflect.Descriptor instead.
func (*AppendEntriesResp) Descriptor() ([]byte, []int) {
	return file_protos_raft_proto_rawDescGZIP(), []int{1}
}

func (x *AppendEntriesResp) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RequestVoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	LastLogIndex  int64                  `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm   int64                  `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteReq) Reset() {
	*x = RequestVoteReq{}
	mi := &file_protos_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteReq) ProtoMessage() {}

func (x *RequestVoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteReq.ProtoReflect.Descriptor instead.
func (*RequestVoteReq) Descriptor() ([]byte, []int) {
	return file_protos_raft_proto_rawDescGZIP(), []int{2}
}

func (x *RequestVoteReq) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteReq) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *RequestVoteReq) GetLastLogIndex() int64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteReq) GetLastLogTerm() int64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResp) Reset() {
	*x = RequestVoteResp{}
	mi := &file_protos_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResp) ProtoMessage() {}

func (x *RequestVoteResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResp.ProtoReflect.Descriptor instead.
func (*RequestVoteResp) Descriptor() ([]byte, []int) {
	return file_protos_raft_proto_rawDescGZIP(), []int{3}
}

func (x *RequestVoteResp) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResp) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Term          int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Index         int64                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	AppendedAt    int64                  `protobuf:"varint,4,opt,name=appendedAt,proto3" json:"appendedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_protos_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_protos_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_protos_raft_proto_rawDescGZIP(), []int{4}
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Entry) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Entry) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Entry) GetAppendedAt() int64 {
	if x != nil {
		return x.AppendedAt
	}
	return 0
}

type SetValueReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValueReq) Reset() {
	*x = SetValueReq{}
	mi := &file_protos_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueReq) ProtoMessage() {}

func (x *SetValueReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueReq.ProtoReflect.Descriptor instead.
func (*SetValueReq) Descriptor() ([]byte, []int) {
	return file_protos_raft_proto_rawDescGZIP(), []int{5}
}

func (x *SetValueReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetValueReq) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetValueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValueResp) Reset() {
	*x = SetValueResp{}
	mi := &file_protos_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueResp) ProtoMessage() {}

func (x *SetValueResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueResp.ProtoReflect.Descriptor instead.
func (*SetValueResp) Descriptor() ([]byte, []int) {
	return file_protos_raft_proto_rawDescGZIP(), []int{6}
}

func (x *SetValueResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetValueReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueReq) Reset() {
	*x = GetValueReq{}
	mi := &file_protos_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueReq) ProtoMessage() {}

func (x *GetValueReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueReq.ProtoReflect.Descriptor instead.
func (*GetValueReq) Descriptor() ([]byte, []int) {
	return file_protos_raft_proto_rawDescGZIP(), []int{7}
}

func (x *GetValueReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetValueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueResp) Reset() {
	*x = GetValueResp{}
	mi := &file_protos_raft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueResp) ProtoMessage() {}

func (x *GetValueResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_raft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueResp.ProtoReflect.Descriptor instead.
func (*GetValueResp) Descriptor() ([]byte, []int) {
	return file_protos_raft_proto_rawDescGZIP(), []int{8}
}

func (x *GetValueResp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetValueResp) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type DeleteValueReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteValueReq) Reset() {
	*x = DeleteValueReq{}
	mi := &file_protos_raft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteValueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValueReq) ProtoMessage() {}

func (x *DeleteValueReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_raft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValueReq.ProtoReflect.Descriptor instead.
func (*DeleteValueReq) Descriptor() ([]byte, []int) {
	return file_protos_raft_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteValueReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteValueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteValueResp) Reset() {
	*x = DeleteValueResp{}
	mi := &file_protos_raft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteValueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValueResp) ProtoMessage() {}

func (x *DeleteValueResp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_raft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValueResp.ProtoReflect.Descriptor instead.
func (*DeleteValueResp) Descriptor() ([]byte, []int) {
	return file_protos_raft_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteValueResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_protos_raft_proto protoreflect.FileDescriptor

const file_protos_raft_proto_rawDesc = "" +
	"\n" +
	"\x11protos/raft.proto\x12\x04raft\"\xd3\x01\n" +
	"\x10AppendEntriesReq\x12%\n" +
	"\aentries\x18\x01 \x03(\v2\v.raft.EntryR\aentries\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12\x1a\n" +
	"\bleaderId\x18\x03 \x01(\tR\bleaderId\x12\"\n" +
	"\fprevLogIndex\x18\x04 \x01(\x03R\fprevLogIndex\x12 \n" +
	"\vprevLogTerm\x18\x05 \x01(\x03R\vprevLogTerm\x12\"\n" +
	"\fleaderCommit\x18\x06 \x01(\x03R\fleaderCommit\"A\n" +
	"\x11AppendEntriesResp\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x8c\x01\n" +
	"\x0eRequestVoteReq\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12 \n" +
	"\vcandidateId\x18\x02 \x01(\tR\vcandidateId\x12\"\n" +
	"\flastLogIndex\x18\x03 \x01(\x03R\flastLogIndex\x12 \n" +
	"\vlastLogTerm\x18\x04 \x01(\x03R\vlastLogTerm\"G\n" +
	"\x0fRequestVoteResp\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12 \n" +
	"\vvoteGranted\x18\x02 \x01(\bR\vvoteGranted\"e\n" +
	"\x05Entry\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x03R\x05index\x12\x1e\n" +
	"\n" +
	"appendedAt\x18\x04 \x01(\x03R\n" +
	"appendedAt\"5\n" +
	"\vSetValueReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"(\n" +
	"\fSetValueResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1f\n" +
	"\vGetValueReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\":\n" +
	"\fGetValueResp\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\"\n" +
	"\x0eDeleteValueReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"+\n" +
	"\x0fDeleteValueResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa6\x02\n" +
	"\x04Raft\x12@\n" +
	"\rAppendEntries\x12\x16.raft.AppendEntriesReq\x1a\x17.raft.AppendEntriesResp\x12:\n" +
	"\vRequestVote\x12\x14.raft.RequestVoteReq\x1a\x15.raft.RequestVoteResp\x121\n" +
	"\bSetValue\x12\x11.raft.SetValueReq\x1a\x12.raft.SetValueResp\x121\n" +
	"\bGetValue\x12\x11.raft.GetValueReq\x1a\x12.raft.GetValueResp\x12:\n" +
	"\vDeleteValue\x12\x14.raft.DeleteValueReq\x1a\x15.raft.DeleteValueRespB\n" +
	"Z\b./protosb\x06proto3"

var (
	file_protos_raft_proto_rawDescOnce sync.Once
	file_protos_raft_proto_rawDescData []byte
)

func file_protos_raft_proto_rawDescGZIP() []byte {
	file_protos_raft_proto_rawDescOnce.Do(func() {
		file_protos_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_raft_proto_rawDesc), len(file_protos_raft_proto_rawDesc)))
	})
	return file_protos_raft_proto_rawDescData
}

var file_protos_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protos_raft_proto_goTypes = []any{
	(*AppendEntriesReq)(nil),  // 0: raft.AppendEntriesReq
	(*AppendEntriesResp)(nil), // 1: raft.AppendEntriesResp
	(*RequestVoteReq)(nil),    // 2: raft.RequestVoteReq
	(*RequestVoteResp)(nil),   // 3: raft.RequestVoteResp
	(*Entry)(nil),             // 4: raft.Entry
	(*SetValueReq)(nil),       // 5: raft.SetValueReq
	(*SetValueResp)(nil),      // 6: raft.SetValueResp
	(*GetValueReq)(nil),       // 7: raft.GetValueReq
	(*GetValueResp)(nil),      // 8: raft.GetValueResp
	(*DeleteValueReq)(nil),    // 9: raft.DeleteValueReq
	(*DeleteValueResp)(nil),   // 10: raft.DeleteValueResp
}
var file_protos_raft_proto_depIdxs = []int32{
	4,  // 0: raft.AppendEntriesReq.entries:type_name -> raft.Entry
	0,  // 1: raft.Raft.AppendEntries:input_type -> raft.AppendEntriesReq
	2,  // 2: raft.Raft.RequestVote:input_type -> raft.RequestVoteReq
	5,  // 3: raft.Raft.SetValue:input_type -> raft.SetValueReq
	7,  // 4: raft.Raft.GetValue:input_type -> raft.GetValueReq
	9,  // 5: raft.Raft.DeleteValue:input_type -> raft.DeleteValueReq
	1,  // 6: raft.Raft.AppendEntries:output_type -> raft.AppendEntriesResp
	3,  // 7: raft.Raft.RequestVote:output_type -> raft.RequestVoteResp
	6,  // 8: raft.Raft.SetValue:output_type -> raft.SetValueResp
	8,  // 9: raft.Raft.GetValue:output_type -> raft.GetValueResp
	10, // 10: raft.Raft.DeleteValue:output_type -> raft.DeleteValueResp
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_protos_raft_proto_init() }
func file_protos_raft_proto_init() {
	if File_protos_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_raft_proto_rawDesc), len(file_protos_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_raft_proto_goTypes,
		DependencyIndexes: file_protos_raft_proto_depIdxs,
		MessageInfos:      file_protos_raft_proto_msgTypes,
	}.Build()
	File_protos_raft_proto = out.File
	file_protos_raft_proto_goTypes = nil
	file_protos_raft_proto_depIdxs = nil
}
